### ISSUE TITLE
File writting

### ISSUE THREAD

**Issue by emiluzelac** [CherryFramework/cherryframework4#14]
[fwrite](https://github.com/CherryFramework/cherryframework4/blob/93fab791294de1768e8c60bdcd9cf8794303c8b6/lib/extensions/class-scss.inc.php#L758) is not safe and should be replaced with `WP_Filesystem` method.

---

See [Filesystem_API](https://codex.wordpress.org/Filesystem_API) and [this post](http://ottopress.com/2011/tutorial-using-the-wp_filesystem/)

**Comment by MjHead** [comment]
Fixed in develop branch
