### ISSUE TITLE
String writing 

### ISSUE THREAD

**Issue by emiluzelac** [CherryFramework/cherryframework4#15]
`file_put_contents` is also not safe and should be replaced with `WP_Filesystem`.

Found in [class-scss-compiler.php](https://github.com/CherryFramework/cherryframework4/blob/93fab791294de1768e8c60bdcd9cf8794303c8b6/lib/extensions/class-scss-compiler.php#L22) and [class-scss.inc.php](https://github.com/CherryFramework/cherryframework4/blob/93fab791294de1768e8c60bdcd9cf8794303c8b6/lib/extensions/class-scss.inc.php#L4313-L4314)

Related #14

**Comment by MjHead** [comment]
Fixed in develop branch
