### ISSUE TITLE
File string reading

### ISSUE THREAD

**Issue by emiluzelac** [CherryFramework/cherryframework4#16]
Just like related #14, #15 `file_get_contents` is not safe either and should be replaced with the `WP_Filesystem`. Found in [class-scss-compiler.php](https://github.com/CherryFramework/cherryframework4/blob/93fab791294de1768e8c60bdcd9cf8794303c8b6/lib/extensions/class-scss-compiler.php#L15), [class-interface-builder.php.txt](https://github.com/CherryFramework/cherryframework4/blob/c2a74551cbc80e5af321e939b656c12b5251b157/docs/api/files/lib/classes/class-interface-builder.php.txt#L668) - (Probably not used and if not please delete the file) and [class-scss.inc.php](https://github.com/CherryFramework/cherryframework4/blob/93fab791294de1768e8c60bdcd9cf8794303c8b6/lib/extensions/class-scss.inc.php#L4288-L4306)

**Comment by MjHead** [comment]
Fixed in develop branch
