### ISSUE TITLE
Theme activation

### ISSUE THREAD

**Issue by emiluzelac** [CherryFramework/cherryframework4#18]
This is what I can see once the theme is activated. Is that normal? To me it looks like styles are not loading completely.

![screen shot 2015-04-23 at 2 17 16 pm](https://cloud.githubusercontent.com/assets/1784526/7305631/f1a6cdfa-e9c4-11e4-94c8-4af3b857c0aa.png)
![screen shot 2015-04-23 at 2 17 39 pm](https://cloud.githubusercontent.com/assets/1784526/7305632/f1a8358c-e9c4-11e4-8c20-c30e8394bbed.png)

**Comment by cheh** [comment]
fixed
