### ISSUE TITLE
Shortcodes

### ISSUE THREAD

**Issue by emiluzelac** [CherryFramework/cherryframework4#21]
[shortcodes.php](https://github.com/CherryFramework/cherryframework4/blob/93fab791294de1768e8c60bdcd9cf8794303c8b6/lib/functions/shortcodes.php) are plugin-territory. 

Also note that every time shortcodes are called they open a [big regex](https://core.trac.wordpress.org/browser/trunk/src/wp-includes/shortcodes.php) as well. If the theme does not really need, I would recommend not using them.

**Comment by justintadlock** [comment]
I also want to add that these lines from `class-cherry-framework.php` should be removed:

```
add_filter( 'widget_text',      'do_shortcode' );
add_filter( 'the_excerpt',      'do_shortcode' );
add_filter( 'term_description', 'do_shortcode' );
add_filter( 'comment_text',     'do_shortcode' );
```

In particular, that last line is highly dangerous:

```
add_filter( 'comment_text',     'do_shortcode' );
```

Giving site visitors access to shortcodes via comments can potentially give them some very powerful tools and is not recommended at all.

**Comment by cheh** [comment]
Also we removed all shortcodes from `cherryframework4`
