### ISSUE TITLE
add_theme_support( "title-tag" ) 

### ISSUE THREAD

**Issue by emiluzelac** [CherryFramework/cherryframework4#23]
It would be great to [incorporate](https://github.com/Automattic/_s/blob/f0de1c9e8b6fa83ec8b32d8b259425d5e5d76fe7/functions.php#L37-L42) `add_theme_support( "title-tag" )` support and let the core manage it.

**Comment by cheh** [comment]
https://github.com/CherryFramework/cherryframework4/commit/7b0d50e696aeb92c2e118174ba51e90c8eaae07d
