### ISSUE TITLE
Prefixing: Image size names

### ISSUE THREAD

**Issue by emiluzelac** [CherryFramework/cherryframework4#3]
Framework did a pretty good job with prefixing, we just need to ensure that all parts follow the same path, like image [size names](https://github.com/CherryFramework/cherryframework4/blob/master/inc/init.php#L38) for example.

`add_image_size( 'slider-post-thumbnail', 1025, 500, true );`

---

Also [see](http://themereview.co/prefix-all-the-things/)

**Comment by cheh** [comment]
https://github.com/CherryFramework/cherryframework4/blob/develop/init/config/thumbnails.php
