### ISSUE TITLE
Blockquote border

### ISSUE THREAD

**Issue by justintadlock** [CherryFramework/cherryframework4#30]
The left border on blockquotes needs a little spacing.  See screenshot.

![blockquote](https://cloud.githubusercontent.com/assets/1816309/7333950/3b16e0dc-eb47-11e4-83e5-3d7710e9f96b.png)

**Comment by MjHead** [comment]
fixed - https://github.com/CherryFramework/cherryframework4/commit/5483699a2201f36e77828f5ebe5d32f0f7a81f49
