### ISSUE TITLE
Table styles

### ISSUE THREAD

**Issue by justintadlock** [CherryFramework/cherryframework4#32]
The `<table>` and related HTML elements could use a little style love.  See screenshot.

![tables](https://cloud.githubusercontent.com/assets/1816309/7333983/782009c6-eb48-11e4-8b92-3e7e03ce4bd0.png)

**Comment by MjHead** [comment]
fixed - https://github.com/CherryFramework/cherryframework4/commit/5483699a2201f36e77828f5ebe5d32f0f7a81f49
