### ISSUE TITLE
Body copy italic

### ISSUE THREAD

**Issue by justintadlock** [CherryFramework/cherryframework4#33]
The primary font used in the theme is italic.  Everything is italic.  It makes things very hard to read.  Italics should only be used to emphasize specific text, not used for all text.

![body-copy](https://cloud.githubusercontent.com/assets/1816309/7333996/0fc09b9c-eb49-11e4-85cc-711fb0b1dd8f.png)

**Comment by cheh** [comment]
Fixed - https://github.com/CherryFramework/cherryframework4/blob/develop/cherry-options.php#L925
