### ISSUE TITLE
"linked" code logic

### ISSUE THREAD

**Issue by justintadlock** [CherryFramework/cherryframework4#34]
I wasn't sure what to title this ticket, but it refers to the `cherry_get_the_post_title()` function: https://github.com/CherryFramework/cherryframework4/blob/master/lib/functions/template-post.php#L153

Basically, there's this check:

```
'linked' => is_singular( $post_type ) ? 'no' : 'yes',
```

Using the strings `'yes'` and `'no'` there is kind of odd and just complicates the code.  All you need to do is this:

```
'linked' => is_singular( $post_type ),
```

Then, later in the function, check against the boolean `true` or `false` instead of `'yes'` and `'no'` strings.

**Comment by cheh** [comment]
This function is used for processing options in a .*tmpl files (files for outputting content) -https://github.com/CherryFramework/cherryframework4/blob/develop/content/related-post.tmpl#L2

And us seems that end-user likes using parameters "yes/no"
