### ISSUE TITLE
Languages: cherry.pot

### ISSUE THREAD

**Issue by emiluzelac** [CherryFramework/cherryframework4#4]
Looking at the [cherry.pot](https://github.com/CherryFramework/cherryframework4/blob/master/languages/cherry.pot) it seems that `_s` theme defaults are still there. Please regenerate.

**Comment by cheh** [comment]
https://github.com/CherryFramework/cherryframework4/blob/develop/languages/blank.pot

**Comment by emiluzelac** [comment]
Keep the name the same cherry not blank :)
