### ISSUE TITLE
Custom menus

### ISSUE THREAD

**Issue by emiluzelac** [CherryFramework/cherryframework4#42]
[../menus.php](https://github.com/CherryFramework/cherryframework4/blob/master/init/config/menus.php#L20)

---

I believe that `register_nav_menus` would be [more appropriate](https://codex.wordpress.org/Function_Reference/register_nav_menus) because we're registering 2 custom menus. 

This will also drop few lines of code as well.

**Comment by cheh** [comment]
Really more appropriate -
https://github.com/CherryFramework/cherryframework4/commit/737ed6dbc3145613bd5aff4d0a50106e72729b92
