### ISSUE TITLE
Plugin territory: cache, time constants

### ISSUE THREAD

**Issue by emiluzelac** [CherryFramework/cherryframework4#44]
[../footer-logo.php](https://github.com/CherryFramework/cherryframework4/blob/master/init/statics/footer-logo.php)
[../header-logo.php](https://github.com/CherryFramework/cherryframework4/blob/master/init/statics/header-logo.php)

---

Themes should avoid using any type of caching or time constants.

**Comment by cheh** [comment]
We remove this functionality from `cherryframework4`.
