### ISSUE TITLE
Microformats 

### ISSUE THREAD

**Issue by emiluzelac** [CherryFramework/cherryframework4#51]
[../head.php](https://github.com/CherryFramework/cherryframework4/blob/master/lib/functions/head.php)

---

I was looking for `<link rel="profile" href="http://gmpg.org/xfn/11">` but could not find it?

**Comment by cheh** [comment]
Added - https://github.com/CherryFramework/cherryframework4/commit/a1100b8fcee4c634f3fcd1339df177da5929c2bc
