### ISSUE TITLE
RTL: stylesheet and support

### ISSUE THREAD

**Issue by emiluzelac** [CherryFramework/cherryframework4#52]
[../rtl.css](https://github.com/CherryFramework/cherryframework4/blob/master/rtl.css)

---

Theme doesn't use `rtl-language-support` tag and the stylesheet is empty, therefore you can freely remove this unused file.

**Comment by cheh** [comment]
Added a rtl-support https://github.com/CherryFramework/cherryframework4/commit/8c8a4d8ce860438d8d7fd87a28dbff579a989be3
