### ISSUE TITLE
Swiper crop_image not working

### ISSUE THREAD

**Issue by krbvroc1** [CherryFramework/cherryframework4#56]
Unsure if this is the correct place to file this issue. I just downloaded the framework and installed the free 'cherryone' theme via the cherry wizard. On the home page the images of the 'team' are missing.

![team](https://cloud.githubusercontent.com/assets/1335118/8865752/c8828fea-3181-11e5-9104-beb669bd43ec.png)

This image was derived from the 'cherry_swiper_carousel'. If I change crop_image to "no", there are some huge images, but at least there are some images. But the default crop_image of "yes" results in no images as all, not even in the markup I am thinking this is a bug. I also updated to 4.0.1 to double check and the problem remains. This is all on a clean WP install.

**Comment by cheh** [comment]
This issue goes hrere - https://github.com/CherryFramework/cherry-shortcodes/issues/2

**Comment by krbvroc1** [comment]
@cheh sorry, thanks for moving.
