### ISSUE TITLE
Video Post Format

### ISSUE THREAD

**Issue by cedisoftsrl** [CherryFramework/cherryframework4#58]
Hi,
It would be nice to be able to set Autoplay and poster. 

Thank you.

**Comment by cheh** [comment]
Hi, cedisoftsrl.
You may to set autoplay and poster in Video Details:
![1](https://cloud.githubusercontent.com/assets/2461627/9384395/e8c75abe-4758-11e5-8e12-851cd991c5ce.png)
![2](https://cloud.githubusercontent.com/assets/2461627/9384400/ed7aa796-4758-11e5-9cf2-fe68267e5c7d.png)
![3](https://cloud.githubusercontent.com/assets/2461627/9384406/f3c43748-4758-11e5-95a7-2b765c7f8ac7.png)
