### ISSUE TITLE
CherryFramework 4.0.5.1 Install error

### ISSUE THREAD

**Issue by chidinweke** [CherryFramework/cherryframework4#63]
Hello

I downloaded the CherryFramework 4.0.5.1 and i'm getting this error.

Fatal error: Call to undefined function wp_styles() in C:\wamp\www\frameworkbootframe\wp-content\themes\cherry\lib\classes\class-cherry-api-js.php on line 71

Screeenshot https://gyazo.com/23c40f03f2ea1d68473e652210496ee3

**Comment by cheh** [comment]
Hello, @chidinweke.
Upgrade your WordPress engine to the latest version, because `wp_styles` function since 4.0.2.
