### ISSUE TITLE
Textdomains: theme-options-sets.php

### ISSUE THREAD

**Issue by emiluzelac** [CherryFramework/cherryframework4#7]
Just like the rest of the framework, [theme-options-page.php](https://github.com/CherryFramework/cherryframework4/blob/ed3a5f2f2d688f4f0acc23d26956addba307b808/lib/admin/pages/theme-options-page.php) would also need to be translatable.

Example: `'name' => __( 'General', 'textdomain' ),`

**Comment by cheh** [comment]
Thanks!
